version: '2'
services:
  ldap-host:
    # image: "osixia/openldap:1.1.2"
    build:
      context: ./image
      dockerfile: Dockerfile
      # args:
      #   buildno: 1
    domainname: tincan.ch
    hostname: ldap
    networks:
      - default
      - ldap
    extends:
      service: ldap-variables
      file: docker-compose-variables.yaml
    volumes:
      - ./var/lib/ldap:/var/lib/ldap:rw
      - ./etc/ldap/slapd.d:/etc/ldap/slapd.d:rw
    restart: always
#    expose:
#      - "389"
#    ports:
#      - "389:389"
  ldap-admin:
    image: "osixia/phpldapadmin:0.6.8"
    depends_on:
      - ldap-host
    links:
      - ldap-host
    extends:
      service: ldap-variables
      file:  docker-compose-variables.yaml
    volumes:
      - ./data/environment/env.yaml:/container/environment/01-custom/env.yaml
    # command: --loglevel debug
    restart: always
#    expose:
#      - "80"
#      - "443"
    ports:
      - "8000:443"
    environment:
      - PHPLDAPADMIN_SERVER_ADMIN=michael@faille.io
      - PHPLDAPADMIN_HTTPS=true
      - PHPLDAPADMIN_LDAP_CLIENT_TLS=false
networks:
  ldap:
    driver: bridge
